## 패키지
pip install 패키지이름  
import 모듈이름 as 설정 이름

# Numpy

* [1. Array](#chapter1)
* [2. Numpy 함수](#chapter2)

In [2]:
import numpy as np

<a class="anchor" id="chapter1"></a>
## 1. Array

+ 배열 vs 리스트 비교

In [5]:
#array 배열
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [6]:
# 리스트
b = [[1,2],[3,4]]
b

[[1, 2], [3, 4]]

In [7]:
a[1,1]

4

In [8]:
b[1][1]

4

## 배열 만들기

### 1차원 배열 만들기

In [9]:
data1 = [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [10]:
data2 = [1,2,3.5,4]
data2

[1, 2, 3.5, 4]

In [12]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [14]:
# array의 형태(크기)를 확인
arr1.shape

(5,)

In [16]:
# array의 자료형을 확인
arr1.dtype

dtype('int32')

In [13]:
arr2 = np.array(data2)
arr2

array([1. , 2. , 3.5, 4. ])

In [15]:
# array의 형태(크기)를 확인
arr2.shape

(4,)

In [17]:
# array의 자료형을 확인
arr2.dtype

dtype('float64')

### 2차원 배열 만들기

In [18]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
arr4.shape

(4, 3)

### 3차원 배열 만들기

In [22]:
arr5=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
                 [[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])
arr5

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [23]:
arr5.shape

(2, 4, 3)

In [27]:
type(arr5)

numpy.ndarray

### 기타 배열 만드는 함수

In [30]:
# np.zeros() : 인자로 받는 크기만큼, 모든요소가 0인 array를 만듬
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
# np.ones() : 인자로 받는 크기만큼, 모든요소가 1인 array를 만듬
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
# np.arange() : 인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만듬
# 이때 하나의 인자만 입력하면 0 ~ 입력한 인자, 값 만큼의 크기를 가짐
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# np.full() : (N,N) shape을 특정값으로 채움
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [37]:
# np.eye() : (N,N) shape의 단위 행렬을 생성
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
# np.empty() : 초기화되지 않은 값으로 zeros나 ones와 마찬가지로 배열을 생성
np.empty((4,2))

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [40]:
# np.zeros_like(), np.ones_like(), np.empty_like()
# array와 동일한 모양과 데이터 형태를 유지한 상태에서 각 각 '0', '1', '빈 배열'을 반환
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [46]:
np.empty_like(a)

array([[        0,         1,         0],
       [858995505,       904,         0],
       [      768,       182, 993090402]])

### Array 연산
연산을 할 떄는 크기가 서로 동일한 array 끼리 연산

In [48]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
arr1.shape

(2, 3)

In [4]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [51]:
arr2.shape

(2, 3)

In [52]:
# array 덧셈
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [53]:
# array 뺄셈
arr1 - arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [55]:
# array 곱셈
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [56]:
# array 나눗셈
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

### Array의 브로드 캐스트
브로드 캐스트 : 서로 크기가 다른 array가 연산이 가능

In [58]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [60]:
arr3.shape

(3,)

In [61]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [62]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [63]:
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

### Arrary의 인덱싱

In [65]:
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [67]:
arr2[0,1]

11

In [68]:
# 모든 열의 3번째 요소 꺼내기
arr2[:,2]

array([12, 15])

In [71]:
# 행의 순서 변경하기
arr2[[1,0],:]

array([[13, 14, 15],
       [10, 11, 12]])

### Array boolean 인덱싱(마스크)
원하는 행 또는 열의 값만 뽑아낼 수 있음

In [73]:
# 아래에서 사용되는 np.random.randn() 함수는 기대값이 0이고, 표준편차가 1인 가우시안 정규 분포를 따르는 난수를 발생시키는 함수
# 이 외에도 0~1의 난수를 발생시키는 np.random.rand() 함수도 존재한다.
data = np.random.randn(8,4) #8행 4열로 난수 채움
data

array([[-0.0070214 , -0.49462301,  0.01078647,  0.89139215],
       [-1.08315642,  0.55342068, -0.79380586,  0.2586929 ],
       [-0.47722469, -0.65079311, -0.15312082,  0.7073484 ],
       [-1.14095355, -0.3913039 ,  0.46623135, -1.34603016],
       [-0.88818157, -0.71722514,  0.4259885 ,  0.06055614],
       [ 0.96954274,  1.00151279,  0.95697676,  0.66004425],
       [ 1.10634025,  0.45082403,  0.67156254,  1.43141269],
       [ 1.24821338,  0.45148603, -0.72154367, -2.0633571 ]])

In [15]:
data = np.random.randint(0,100,size=(8,4)) #8행 4열로  0부터 100사이의 정수로 채움
data

array([[98, 66,  6, 72],
       [49, 89,  1, 71],
       [41, 61, 82, 66],
       [52, 23, 38, 59],
       [93,  9, 96, 27],
       [23,  6, 67, 28],
       [15, 28, 47, 94],
       [ 6, 39, 39, 95]])

In [75]:
type(data)

numpy.ndarray

In [76]:
data.shape

(8, 4)

In [77]:
# 먼저 마스크를 만든다.
# data array에서 0번째 열이 50보다 작은 요소의 boolean 값은 다음과 같다.
data[:,0] < 50

array([False, False, False, False,  True, False, False,  True])

In [78]:
# 위에서 만든 마스크를 이용하여 0번째 열의 값이 50보다 작은 행을 구한다.
data[data[:,0]<50,:]

array([[39, 71, 94,  3],
       [40, 92, 40, 37]])

In [79]:
# 0번째 열의 값이 50보다 작은 행의 2,3번째 열 값
data[data[:,0]<50,2:4]

array([[94,  3],
       [40, 37]])

In [80]:
#0번째 열의 값이 50보다 작은 행의 2,3번째 열값에 0을 대입
data[data[:,0]<50,2:4] = 0
data

array([[70,  1, 66, 58],
       [56, 34, 55, 45],
       [64, 67, 57, 22],
       [89, 37, 57, 33],
       [39, 71,  0,  0],
       [58, 74, 40, 49],
       [75, 55, 37, 89],
       [40, 92,  0,  0]])

In [5]:
# boolean을 홀용한 인덱싱
arr2[:, [True, False, False, True]]

IndexError: boolean index did not match indexed array along dimension 1; dimension is 3 but corresponding boolean dimension is 4

In [6]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [7]:
names.shape

(8,)

In [12]:
names[0]

'Beomwoo'

In [13]:
# 요소가 Beomwoo인 항목에 대한 mask 생성
names_Beomwoo_mask = (names == 'Beomwoo')
names_Beomwoo_mask

array([ True,  True, False, False, False,  True, False,  True])

In [16]:
data[names_Beomwoo_mask,:]

array([[98, 66,  6, 72],
       [49, 89,  1, 71],
       [23,  6, 67, 28],
       [ 6, 39, 39, 95]])

<a class="anchor" id="chapter2"></a>
## Numpy 함수

- 하나의 array에 적용되는 함수  
np.abs, np.sqrt, np.square(제곱), np.exp, np.log, np.log10, np.log2  
np.sign(각 성분의 부호 계산기 +인경우 1, -인 경우,-1,0인경우 0)  
np.ceil(소수 한자리 올림), np.floor(소수 한자리 내림)  
np.isnan(NaN인 경우 True를 아니면 False), np.isinf(무한대면 True를 아니면 False)  
np.cos(삼각함수 값을 계산하기)

In [17]:
arr1 = np.random.randint(-100,100,size=(4,3)) #4행 3열로 난수 채움
arr1

array([[  3,  37, -94],
       [ 79,  32, -22],
       [ 12,  -9, -62],
       [-79, -35, -36]])

In [18]:
np.sign(arr1)

array([[ 1,  1, -1],
       [ 1,  1, -1],
       [ 1, -1, -1],
       [-1, -1, -1]])

- 두 개의 array에 적용되는 함수  
np.add(A,B) 더하기, np.subtract(A,B) 빼기, np.multiply(A,B) 곱하기  
np.dibide(A,B) 나누기, np.maximum(A,B) 최대값, np.minimum(A,B) 최소값

In [19]:
arr2 = np.random.randint(-100,100,size=(4,3)) #4행 3열로 난수 채움
arr2

array([[-23, -85, -68],
       [-66,  98, -39],
       [ 77, -94, -26],
       [ 16,  56,  41]])

In [21]:
np.maximum(arr1,arr2)

array([[  3,  37, -68],
       [ 79,  98, -22],
       [ 77,  -9, -26],
       [ 16,  56,  41]])

+ 통계 함수  
np.sum, np.mean, np.std, np.var, np.min, np.max  
np.argmin(최소값이 위치한 인덱스 반환), np.argmax(최대값이 위치한 인덱스 반환)  
np.cumsum(누적합), np.cumprod(누적곱)
- axis = 0 행 / axis = 1 열

In [26]:
# 전체 성분의 최소값, 최대값이 위치한 인덱스를 반환(argmin, argmax)
np.argmin(arr1)

2

In [25]:
np.cumsum(arr1)

array([   3,   40,  -54,   25,   57,   35,   47,   38,  -24, -103, -138,
       -174], dtype=int32)

In [30]:
np.cumsum(arr1,axis = 1)

array([[   3,   40,  -54],
       [  79,  111,   89],
       [  12,    3,  -59],
       [ -79, -114, -150]], dtype=int32)

- np.where 함수
    - where 함수를 이용해서 특정 조건에 맞는 값을 다른 값으로 변환할 수 있음

In [37]:
x = np.array([5, 4, 3, 2, 1, 0])

In [38]:
np.where(x >= 3) #3과 같거나 큰값을 가지는 색인의 위치확인

(array([0, 1, 2], dtype=int64),)

In [39]:
x[np.where(x >= 3)] #조건에 맞는 값을 인덱싱하기

array([5, 4, 3])

In [35]:
##조건에 맞는 값을 특정 다른 값으로 변환하기
#배열의 값이 3과 같거나 크면 3으로 변환하고, 3보다 작으면 그대로 값을 유지
np.where(x >= 3, 3, x)

array([3, 3, 3, 2, 1, 0])

In [40]:
x = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
np.where(x >= 6)

(array([1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [42]:
np.where(x >= 6, 0, x)

array([[1, 2, 3, 4],
       [5, 0, 0, 0],
       [0, 0, 0, 0]])

In [43]:
ids, cols = np.where(x >= 6)

In [44]:
ids

array([1, 1, 1, 2, 2, 2, 2], dtype=int64)

In [45]:
cols

array([1, 2, 3, 0, 1, 2, 3], dtype=int64)

In [46]:
list(zip(ids, cols ))

[(1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3)]

### 정렬함수
np.sort() 열 기준 오름차순 정렬, np.sort(,axis=0)[::-1] 행 기준 내림차순 정렬  
np.sort(,axis=0) 행 기준 오름차순 정렬, np.sort(,axis=1) 열 기준 오름차순 정렬  
np.sort(,axis=1)[:,::-1] 열 기준 내림차순 정렬